#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Set up default index file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is configured to listen on port 80
sudo sed -i 's/# listen 80;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
