#!/usr/bin/env bash
# This script kills the process 7-highlander

# Find the PID of the 7-highlander script
pid=$(pgrep -f "7-highlander")

# Send a SIGKILL signal to terminate the process
kill -9 "$pid"
