#!/usr/bin/env bash
# Bash script that creates an RSA key pair

# Check if the key pair already exists
if [ -e "school" ] || [ -e "school.pub" ]; then
    echo "RSA key pair 'school' already exists."
    exit 1
fi

# Generate the RSA key pair with a passphrase
ssh-keygen -t rsa -b 4096 -f school -C "RSA key pair for school" -N "betty"

# Check if the key pair was successfully created
if [ $? -eq 0 ]; then
    echo "RSA key pair 'school' created successfully."
else
    echo "Error: Failed to create RSA key pair."
    exit 1
fi

